steps:
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=gcr.io/$PROJECT_ID/apps/hello_world:latest"
      - "--file=./Dockerfile"
      - "."
images:
  - "gcr.io/$PROJECT_ID/apps/hello_world:latest"
