source:
  repoSource:
    projectId: docker-images-180022
    repoName: github_sathishavm_hello_world
    branchName: spinnaker
steps:
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=gcr.io/$PROJECT_ID/apps/testhelloworld:latest"
      - "--file=./Dockerfile"
      - "."
images:
  - "gcr.io/$PROJECT_ID/apps/testhelloworld:latest"
