---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-baseline
  namespace: zendesk-dev-pod
  labels:
    project: hello-world
    role: app-server
    version: baseline
spec:
  replicas: 1
  selector:
    matchLabels:
      project: hello-world
      role: app-server
      version: baseline
  template:
    metadata:
      labels:
        project: hello-world
        role: app-server
        version: baseline
      annotations:
        secret/APP_NAME: app_name
        secret/TEAM: team
    spec:
      serviceAccountName: vault-auth
      volumes:
      - name: secrets-volume
        emptyDir:
          medium: Memory
      - name: secretkeys
        downwardAPI:
          items:
          - path: "annotations"
            fieldRef:
              fieldPath: "metadata.annotations"
      initContainers:
      - name: 'secret-puller'
        image: gcr.io/docker-images-180022/apps/samson_secret_puller:latest
        volumeMounts:
        - mountPath: /secretkeys
          name: secretkeys
        - mountPath: /secrets
          name: secrets-volume
        env:
        - name: VAULT_ADDR
          value: http://ec2-54-185-66-250.us-west-2.compute.amazonaws.com:8200
        - name: VAULT_AUTH_TYPE
          value: kubernetes
        - name: VAULT_AUTH_ROLE
          value: hello-world-role
        - name: VAULT_PREFIX
          value: hello-world
      containers:
      - name: default-baseline
        image: gcr.io/docker-images-180022/apps/hello_world
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "Baseline"
        resources:
          requests:
            cpu: '0.2'
            memory: 512M
          limits:
            cpu: '1.0'
            memory: 1024M
        ports:
        - name: main
          containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /secrets
          name: secrets-volume
      imagePullSecrets:
      - name: spinnaker-poc-registry
