---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-production
  labels:
    project: hello-world
    role: app-server
    version: production
spec:
  replicas: 1
  selector:
    matchLabels:
      spinnaker_deploy: "true"
      project: hello-world
      role: app-server
      version: production
  template:
    metadata:
      labels:
        spinnaker_deploy: "true"
        project: hello-world
        role: app-server
        version: production
      annotations:
        secret/APP_NAME: app_name
        secret/TEAM: team
        secret/DEMO: demo
        "vault.security/enabled": "true"
        "configuration.commit": "${ trigger['payload']['sourceProvenance']['resolvedRepoSource']['commitSha'] }"
    spec:
      containers:
      - name: default-production
        image: gcr.io/docker-images-180022/apps/hello_world
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "${ trigger['payload']['sourceProvenance']['resolvedRepoSource']['commitSha'] }"
        ports:
        - name: main
          containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: spinnaker-poc-registry
